### ISSUE TITLE
没有独立显卡的mac电脑，怎么运行代码呀，改成cpu了还一直报错

### ISSUE THREAD

**Issue by antheaxiang** [yhcc/CNN_Nested_NER#6]
Traceback (most recent call last):
  File "/Users/ekko/begin/CNN_Nested_NER-master/train.py", line 204, in <module>
    progress_bar='rich')
  File "/Users/ekko/begin/CNN_Nested_NER-master/fastNLP_10/core/controllers/trainer.py", line 492, in __init__
    **kwargs
  File "/Users/ekko/begin/CNN_Nested_NER-master/fastNLP_10/core/drivers/choose_driver.py", line 37, in choose_driver
    return initialize_torch_driver(driver, device, model, **kwargs)
  File "/Users/ekko/begin/CNN_Nested_NER-master/fastNLP_10/core/drivers/torch_driver/initialize_torch_driver.py", line 86, in initialize_torch_driver
    return TorchSingleDriver(model, device, **kwargs)
  File "/Users/ekko/begin/CNN_Nested_NER-master/fastNLP_10/core/drivers/torch_driver/single_device.py", line 60, in __init__
    super(TorchSingleDriver, self).__init__(model, fp16=fp16, torch_kwargs=torch_kwargs, **kwargs)
  File "/Users/ekko/begin/CNN_Nested_NER-master/fastNLP_10/core/drivers/torch_driver/torch_driver.py", line 62, in __init__
    self.auto_cast, _grad_scaler = _build_fp16_env(dummy=not self.fp16)
  File "/Users/ekko/begin/CNN_Nested_NER-master/fastNLP_10/core/drivers/torch_driver/utils.py", line 174, in _build_fp16_env
    raise RuntimeError("Pytorch is not installed in gpu version, please use device='cpu'.")
RuntimeError: Pytorch is not installed in gpu version, please use device='cpu'.

**Comment by yhcc** [comment]
fp16 set to False
